name: whatch-releases
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: "37 4 * * *" # run every day at 4:37am UTC

jobs:
  watch-releases:
    strategy:
      matrix:
        project:
          - operator-framework/operator-sdk
          - operator-framework/operator-registry
          - gmeghnag/koff
          - gmeghnag/omc
          - openshift-pipelines/opc
    runs-on: ubuntu-latest
    if: github.repository_owner == 'vdemeester'
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit

      - name: ${{ matrix.project }}
        uses: git-for-windows/rss-to-issues@44ef58301d5c8257c00e3ae0a233d9659a5e0f4f # v0.0.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          feed: https://github.com/${{ matrix.project }}/releases.atom
          prefix: "[${{ matrix.project }}]"
          dry-run: false
          max-age: 72h

